---
# tasks file for crictl

- name: Import install_debian.yml if OS family is Debian
  ansible.builtin.import_tasks: install_debian.yml
  when: ansible_os_family == "Debian"

- name: Import install_el.yml if OS family is EL
  ansible.builtin.import_tasks: install_el.yml
  when: ansible_os_family == "RedHat"

- name: Add /etc/crictl.yaml file
  copy:
    dest: /etc/crictl.yaml
    content: |
      runtime-endpoint: "unix:///run/containerd/containerd.sock"
      timeout: 0
      debug: false